services:
  db:
    image: pgvector/pgvector:pg17
    container_name: career-ai-db
    env_file:
      - ./docker/env/database.env
    ports:
      - '5432:5432'
    volumes:
      - ./docker/local-database:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: career-ai-redis
    ports:
      - '6379:6379'
    volumes:
      - ./docker/local-redis:/data
    restart: unless-stopped

  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - ./docker/env/api.env

  llm-worker:
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: apps/llm-worker/Dockerfile
    env_file:
      - ./docker/env/llm-worker.env
